services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: docker/web/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/var/www
  #   environment:
  #     - APP_ENV=local

  backoffice_service:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
    command: [ "php", "-S", "0.0.0.0:8081", "-t", "apps/backoffice/backend/public" ]
